/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as OQueFazemosRouteImport } from './routes/o-que-fazemos'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as NossoCultoRouteImport } from './routes/nosso-culto'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoAjudarRouteImport } from './routes/como-ajudar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as ComoAjudarDoacaoFinanceiraRouteImport } from './routes/como-ajudar.doacao-financeira'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const OQueFazemosRoute = OQueFazemosRouteImport.update({
  id: '/o-que-fazemos',
  path: '/o-que-fazemos',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const NossoCultoRoute = NossoCultoRouteImport.update({
  id: '/nosso-culto',
  path: '/nosso-culto',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoAjudarRoute = ComoAjudarRouteImport.update({
  id: '/como-ajudar',
  path: '/como-ajudar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjetosRoute,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoticiasRoute,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjetosRoute,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NoticiasRoute,
} as any)
const ComoAjudarDoacaoFinanceiraRoute =
  ComoAjudarDoacaoFinanceiraRouteImport.update({
    id: '/doacao-financeira',
    path: '/doacao-financeira',
    getParentRoute: () => ComoAjudarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-ajudar': typeof ComoAjudarRouteWithChildren
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/galeria': typeof GaleriaRoute
  '/nosso-culto': typeof NossoCultoRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/o-que-fazemos': typeof OQueFazemosRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/quem-somos': typeof QuemSomosRoute
  '/transparencia': typeof TransparenciaRoute
  '/como-ajudar/doacao-financeira': typeof ComoAjudarDoacaoFinanceiraRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-ajudar': typeof ComoAjudarRouteWithChildren
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/galeria': typeof GaleriaRoute
  '/nosso-culto': typeof NossoCultoRoute
  '/o-que-fazemos': typeof OQueFazemosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/transparencia': typeof TransparenciaRoute
  '/como-ajudar/doacao-financeira': typeof ComoAjudarDoacaoFinanceiraRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/noticias': typeof NoticiasIndexRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-ajudar': typeof ComoAjudarRouteWithChildren
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/galeria': typeof GaleriaRoute
  '/nosso-culto': typeof NossoCultoRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/o-que-fazemos': typeof OQueFazemosRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/quem-somos': typeof QuemSomosRoute
  '/transparencia': typeof TransparenciaRoute
  '/como-ajudar/doacao-financeira': typeof ComoAjudarDoacaoFinanceiraRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-ajudar'
    | '/contato'
    | '/equipe'
    | '/galeria'
    | '/nosso-culto'
    | '/noticias'
    | '/o-que-fazemos'
    | '/projetos'
    | '/quem-somos'
    | '/transparencia'
    | '/como-ajudar/doacao-financeira'
    | '/noticias/$slug'
    | '/projetos/$slug'
    | '/noticias/'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-ajudar'
    | '/contato'
    | '/equipe'
    | '/galeria'
    | '/nosso-culto'
    | '/o-que-fazemos'
    | '/quem-somos'
    | '/transparencia'
    | '/como-ajudar/doacao-financeira'
    | '/noticias/$slug'
    | '/projetos/$slug'
    | '/noticias'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/como-ajudar'
    | '/contato'
    | '/equipe'
    | '/galeria'
    | '/nosso-culto'
    | '/noticias'
    | '/o-que-fazemos'
    | '/projetos'
    | '/quem-somos'
    | '/transparencia'
    | '/como-ajudar/doacao-financeira'
    | '/noticias/$slug'
    | '/projetos/$slug'
    | '/noticias/'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoAjudarRoute: typeof ComoAjudarRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  EquipeRoute: typeof EquipeRoute
  GaleriaRoute: typeof GaleriaRoute
  NossoCultoRoute: typeof NossoCultoRoute
  NoticiasRoute: typeof NoticiasRouteWithChildren
  OQueFazemosRoute: typeof OQueFazemosRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  QuemSomosRoute: typeof QuemSomosRoute
  TransparenciaRoute: typeof TransparenciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-que-fazemos': {
      id: '/o-que-fazemos'
      path: '/o-que-fazemos'
      fullPath: '/o-que-fazemos'
      preLoaderRoute: typeof OQueFazemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosso-culto': {
      id: '/nosso-culto'
      path: '/nosso-culto'
      fullPath: '/nosso-culto'
      preLoaderRoute: typeof NossoCultoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-ajudar': {
      id: '/como-ajudar'
      path: '/como-ajudar'
      fullPath: '/como-ajudar'
      preLoaderRoute: typeof ComoAjudarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/como-ajudar/doacao-financeira': {
      id: '/como-ajudar/doacao-financeira'
      path: '/doacao-financeira'
      fullPath: '/como-ajudar/doacao-financeira'
      preLoaderRoute: typeof ComoAjudarDoacaoFinanceiraRouteImport
      parentRoute: typeof ComoAjudarRoute
    }
  }
}

interface ComoAjudarRouteChildren {
  ComoAjudarDoacaoFinanceiraRoute: typeof ComoAjudarDoacaoFinanceiraRoute
}

const ComoAjudarRouteChildren: ComoAjudarRouteChildren = {
  ComoAjudarDoacaoFinanceiraRoute: ComoAjudarDoacaoFinanceiraRoute,
}

const ComoAjudarRouteWithChildren = ComoAjudarRoute._addFileChildren(
  ComoAjudarRouteChildren,
)

interface NoticiasRouteChildren {
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasSlugRoute: NoticiasSlugRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

interface ProjetosRouteChildren {
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosSlugRoute: ProjetosSlugRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoAjudarRoute: ComoAjudarRouteWithChildren,
  ContatoRoute: ContatoRoute,
  EquipeRoute: EquipeRoute,
  GaleriaRoute: GaleriaRoute,
  NossoCultoRoute: NossoCultoRoute,
  NoticiasRoute: NoticiasRouteWithChildren,
  OQueFazemosRoute: OQueFazemosRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  QuemSomosRoute: QuemSomosRoute,
  TransparenciaRoute: TransparenciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
