/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as OQueFazemosRouteImport } from './routes/o-que-fazemos'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as NossoCultoRouteImport } from './routes/nosso-culto'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CalendarioLiturgicoRouteImport } from './routes/calendario-liturgico'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as ComoAjudarIndexRouteImport } from './routes/como-ajudar.index'
import { Route as ProjetosPresidenteRouteImport } from './routes/projetos.presidente'
import { Route as ProjetosMaracatuRouteImport } from './routes/projetos.maracatu'
import { Route as ProjetosLgbtqiaRouteImport } from './routes/projetos.lgbtqia'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as ComoAjudarPontoDeColetaRouteImport } from './routes/como-ajudar.ponto-de-coleta'
import { Route as ComoAjudarDoacaoMantimentosRouteImport } from './routes/como-ajudar.doacao-mantimentos'
import { Route as ComoAjudarDoacaoItensRouteImport } from './routes/como-ajudar.doacao-itens'
import { Route as ComoAjudarDoacaoFinanceiraRouteImport } from './routes/como-ajudar.doacao-financeira'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const OQueFazemosRoute = OQueFazemosRouteImport.update({
  id: '/o-que-fazemos',
  path: '/o-que-fazemos',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const NossoCultoRoute = NossoCultoRouteImport.update({
  id: '/nosso-culto',
  path: '/nosso-culto',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioLiturgicoRoute = CalendarioLiturgicoRouteImport.update({
  id: '/calendario-liturgico',
  path: '/calendario-liturgico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjetosRoute,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoticiasRoute,
} as any)
const ComoAjudarIndexRoute = ComoAjudarIndexRouteImport.update({
  id: '/como-ajudar/',
  path: '/como-ajudar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosPresidenteRoute = ProjetosPresidenteRouteImport.update({
  id: '/presidente',
  path: '/presidente',
  getParentRoute: () => ProjetosRoute,
} as any)
const ProjetosMaracatuRoute = ProjetosMaracatuRouteImport.update({
  id: '/maracatu',
  path: '/maracatu',
  getParentRoute: () => ProjetosRoute,
} as any)
const ProjetosLgbtqiaRoute = ProjetosLgbtqiaRouteImport.update({
  id: '/lgbtqia',
  path: '/lgbtqia',
  getParentRoute: () => ProjetosRoute,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjetosRoute,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NoticiasRoute,
} as any)
const ComoAjudarPontoDeColetaRoute = ComoAjudarPontoDeColetaRouteImport.update({
  id: '/como-ajudar/ponto-de-coleta',
  path: '/como-ajudar/ponto-de-coleta',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoAjudarDoacaoMantimentosRoute =
  ComoAjudarDoacaoMantimentosRouteImport.update({
    id: '/como-ajudar/doacao-mantimentos',
    path: '/como-ajudar/doacao-mantimentos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComoAjudarDoacaoItensRoute = ComoAjudarDoacaoItensRouteImport.update({
  id: '/como-ajudar/doacao-itens',
  path: '/como-ajudar/doacao-itens',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoAjudarDoacaoFinanceiraRoute =
  ComoAjudarDoacaoFinanceiraRouteImport.update({
    id: '/como-ajudar/doacao-financeira',
    path: '/como-ajudar/doacao-financeira',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario-liturgico': typeof CalendarioLiturgicoRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/galeria': typeof GaleriaRoute
  '/nosso-culto': typeof NossoCultoRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/o-que-fazemos': typeof OQueFazemosRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/quem-somos': typeof QuemSomosRoute
  '/transparencia': typeof TransparenciaRoute
  '/como-ajudar/doacao-financeira': typeof ComoAjudarDoacaoFinanceiraRoute
  '/como-ajudar/doacao-itens': typeof ComoAjudarDoacaoItensRoute
  '/como-ajudar/doacao-mantimentos': typeof ComoAjudarDoacaoMantimentosRoute
  '/como-ajudar/ponto-de-coleta': typeof ComoAjudarPontoDeColetaRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/lgbtqia': typeof ProjetosLgbtqiaRoute
  '/projetos/maracatu': typeof ProjetosMaracatuRoute
  '/projetos/presidente': typeof ProjetosPresidenteRoute
  '/como-ajudar/': typeof ComoAjudarIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario-liturgico': typeof CalendarioLiturgicoRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/galeria': typeof GaleriaRoute
  '/nosso-culto': typeof NossoCultoRoute
  '/o-que-fazemos': typeof OQueFazemosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/transparencia': typeof TransparenciaRoute
  '/como-ajudar/doacao-financeira': typeof ComoAjudarDoacaoFinanceiraRoute
  '/como-ajudar/doacao-itens': typeof ComoAjudarDoacaoItensRoute
  '/como-ajudar/doacao-mantimentos': typeof ComoAjudarDoacaoMantimentosRoute
  '/como-ajudar/ponto-de-coleta': typeof ComoAjudarPontoDeColetaRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/lgbtqia': typeof ProjetosLgbtqiaRoute
  '/projetos/maracatu': typeof ProjetosMaracatuRoute
  '/projetos/presidente': typeof ProjetosPresidenteRoute
  '/como-ajudar': typeof ComoAjudarIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario-liturgico': typeof CalendarioLiturgicoRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/galeria': typeof GaleriaRoute
  '/nosso-culto': typeof NossoCultoRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/o-que-fazemos': typeof OQueFazemosRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/quem-somos': typeof QuemSomosRoute
  '/transparencia': typeof TransparenciaRoute
  '/como-ajudar/doacao-financeira': typeof ComoAjudarDoacaoFinanceiraRoute
  '/como-ajudar/doacao-itens': typeof ComoAjudarDoacaoItensRoute
  '/como-ajudar/doacao-mantimentos': typeof ComoAjudarDoacaoMantimentosRoute
  '/como-ajudar/ponto-de-coleta': typeof ComoAjudarPontoDeColetaRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/lgbtqia': typeof ProjetosLgbtqiaRoute
  '/projetos/maracatu': typeof ProjetosMaracatuRoute
  '/projetos/presidente': typeof ProjetosPresidenteRoute
  '/como-ajudar/': typeof ComoAjudarIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario-liturgico'
    | '/contato'
    | '/equipe'
    | '/galeria'
    | '/nosso-culto'
    | '/noticias'
    | '/o-que-fazemos'
    | '/projetos'
    | '/quem-somos'
    | '/transparencia'
    | '/como-ajudar/doacao-financeira'
    | '/como-ajudar/doacao-itens'
    | '/como-ajudar/doacao-mantimentos'
    | '/como-ajudar/ponto-de-coleta'
    | '/noticias/$slug'
    | '/projetos/$slug'
    | '/projetos/lgbtqia'
    | '/projetos/maracatu'
    | '/projetos/presidente'
    | '/como-ajudar/'
    | '/noticias/'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario-liturgico'
    | '/contato'
    | '/equipe'
    | '/galeria'
    | '/nosso-culto'
    | '/o-que-fazemos'
    | '/quem-somos'
    | '/transparencia'
    | '/como-ajudar/doacao-financeira'
    | '/como-ajudar/doacao-itens'
    | '/como-ajudar/doacao-mantimentos'
    | '/como-ajudar/ponto-de-coleta'
    | '/noticias/$slug'
    | '/projetos/$slug'
    | '/projetos/lgbtqia'
    | '/projetos/maracatu'
    | '/projetos/presidente'
    | '/como-ajudar'
    | '/noticias'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/calendario-liturgico'
    | '/contato'
    | '/equipe'
    | '/galeria'
    | '/nosso-culto'
    | '/noticias'
    | '/o-que-fazemos'
    | '/projetos'
    | '/quem-somos'
    | '/transparencia'
    | '/como-ajudar/doacao-financeira'
    | '/como-ajudar/doacao-itens'
    | '/como-ajudar/doacao-mantimentos'
    | '/como-ajudar/ponto-de-coleta'
    | '/noticias/$slug'
    | '/projetos/$slug'
    | '/projetos/lgbtqia'
    | '/projetos/maracatu'
    | '/projetos/presidente'
    | '/como-ajudar/'
    | '/noticias/'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioLiturgicoRoute: typeof CalendarioLiturgicoRoute
  ContatoRoute: typeof ContatoRoute
  EquipeRoute: typeof EquipeRoute
  GaleriaRoute: typeof GaleriaRoute
  NossoCultoRoute: typeof NossoCultoRoute
  NoticiasRoute: typeof NoticiasRouteWithChildren
  OQueFazemosRoute: typeof OQueFazemosRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  QuemSomosRoute: typeof QuemSomosRoute
  TransparenciaRoute: typeof TransparenciaRoute
  ComoAjudarDoacaoFinanceiraRoute: typeof ComoAjudarDoacaoFinanceiraRoute
  ComoAjudarDoacaoItensRoute: typeof ComoAjudarDoacaoItensRoute
  ComoAjudarDoacaoMantimentosRoute: typeof ComoAjudarDoacaoMantimentosRoute
  ComoAjudarPontoDeColetaRoute: typeof ComoAjudarPontoDeColetaRoute
  ComoAjudarIndexRoute: typeof ComoAjudarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-que-fazemos': {
      id: '/o-que-fazemos'
      path: '/o-que-fazemos'
      fullPath: '/o-que-fazemos'
      preLoaderRoute: typeof OQueFazemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosso-culto': {
      id: '/nosso-culto'
      path: '/nosso-culto'
      fullPath: '/nosso-culto'
      preLoaderRoute: typeof NossoCultoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario-liturgico': {
      id: '/calendario-liturgico'
      path: '/calendario-liturgico'
      fullPath: '/calendario-liturgico'
      preLoaderRoute: typeof CalendarioLiturgicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/como-ajudar/': {
      id: '/como-ajudar/'
      path: '/como-ajudar'
      fullPath: '/como-ajudar/'
      preLoaderRoute: typeof ComoAjudarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/presidente': {
      id: '/projetos/presidente'
      path: '/presidente'
      fullPath: '/projetos/presidente'
      preLoaderRoute: typeof ProjetosPresidenteRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/projetos/maracatu': {
      id: '/projetos/maracatu'
      path: '/maracatu'
      fullPath: '/projetos/maracatu'
      preLoaderRoute: typeof ProjetosMaracatuRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/projetos/lgbtqia': {
      id: '/projetos/lgbtqia'
      path: '/lgbtqia'
      fullPath: '/projetos/lgbtqia'
      preLoaderRoute: typeof ProjetosLgbtqiaRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/como-ajudar/ponto-de-coleta': {
      id: '/como-ajudar/ponto-de-coleta'
      path: '/como-ajudar/ponto-de-coleta'
      fullPath: '/como-ajudar/ponto-de-coleta'
      preLoaderRoute: typeof ComoAjudarPontoDeColetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-ajudar/doacao-mantimentos': {
      id: '/como-ajudar/doacao-mantimentos'
      path: '/como-ajudar/doacao-mantimentos'
      fullPath: '/como-ajudar/doacao-mantimentos'
      preLoaderRoute: typeof ComoAjudarDoacaoMantimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-ajudar/doacao-itens': {
      id: '/como-ajudar/doacao-itens'
      path: '/como-ajudar/doacao-itens'
      fullPath: '/como-ajudar/doacao-itens'
      preLoaderRoute: typeof ComoAjudarDoacaoItensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-ajudar/doacao-financeira': {
      id: '/como-ajudar/doacao-financeira'
      path: '/como-ajudar/doacao-financeira'
      fullPath: '/como-ajudar/doacao-financeira'
      preLoaderRoute: typeof ComoAjudarDoacaoFinanceiraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NoticiasRouteChildren {
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasSlugRoute: NoticiasSlugRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

interface ProjetosRouteChildren {
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  ProjetosLgbtqiaRoute: typeof ProjetosLgbtqiaRoute
  ProjetosMaracatuRoute: typeof ProjetosMaracatuRoute
  ProjetosPresidenteRoute: typeof ProjetosPresidenteRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosSlugRoute: ProjetosSlugRoute,
  ProjetosLgbtqiaRoute: ProjetosLgbtqiaRoute,
  ProjetosMaracatuRoute: ProjetosMaracatuRoute,
  ProjetosPresidenteRoute: ProjetosPresidenteRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioLiturgicoRoute: CalendarioLiturgicoRoute,
  ContatoRoute: ContatoRoute,
  EquipeRoute: EquipeRoute,
  GaleriaRoute: GaleriaRoute,
  NossoCultoRoute: NossoCultoRoute,
  NoticiasRoute: NoticiasRouteWithChildren,
  OQueFazemosRoute: OQueFazemosRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  QuemSomosRoute: QuemSomosRoute,
  TransparenciaRoute: TransparenciaRoute,
  ComoAjudarDoacaoFinanceiraRoute: ComoAjudarDoacaoFinanceiraRoute,
  ComoAjudarDoacaoItensRoute: ComoAjudarDoacaoItensRoute,
  ComoAjudarDoacaoMantimentosRoute: ComoAjudarDoacaoMantimentosRoute,
  ComoAjudarPontoDeColetaRoute: ComoAjudarPontoDeColetaRoute,
  ComoAjudarIndexRoute: ComoAjudarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
